/** Typed client for the CaptionGrab Cloudflare Worker API. */

import { API_BASE_URL, API_TIMEOUT_MS } from "@/config/apiConfig";

export interface ApiCaptionTrack {
  languageCode: string;
  languageName: string;
  kind: "manual" | "auto";
  translatable: boolean;
}

export interface VideoInfo {
  videoId: string;
  title: string;
  author: string;
  lengthSeconds: number;
  viewCount: number | null;
  thumbnail: string;
  captionsAvailable: boolean;
  tracks: ApiCaptionTrack[];
  /** True when served by the dev-server offline demo library instead of the Worker. */
  demo?: boolean;
}

export interface TranscriptSegment {
  start: number;
  dur: number;
  text: string;
}

export interface TranscriptResult {
  videoId: string;
  title: string;
  author: string;
  requestedLanguage: string;
  language: string;
  languageName: string;
  /** Language of the underlying caption track (differs from `language` when translated). */
  sourceLanguage?: string;
  sourceLanguageName?: string;
  isAutoGenerated: boolean;
  translated: boolean;
  segments: TranscriptSegment[];
  text: string;
  /** True when served by the dev-server offline demo library instead of the Worker. */
  demo?: boolean;
}

export type ApiErrorCode =
  | "INVALID_VIDEO_ID"
  | "VIDEO_NOT_FOUND"
  | "PRIVATE_VIDEO"
  | "UNPLAYABLE_VIDEO"
  | "NO_CAPTIONS"
  | "LANGUAGE_UNAVAILABLE"
  | "TRANSCRIPT_UNAVAILABLE"
  | "RATE_LIMITED"
  | "UPSTREAM_ERROR"
  | "NETWORK_ERROR"
  | "TIMEOUT"
  | "NOT_FOUND"
  | "BAD_REQUEST"
  | "UNKNOWN";

export class CaptionGrabError extends Error {
  code: ApiErrorCode;
  retryAfter?: number;

  constructor(code: ApiErrorCode, message: string, retryAfter?: number) {
    super(message);
    this.name = "CaptionGrabError";
    this.code = code;
    this.retryAfter = retryAfter;
  }
}

function baseUrl(): string {
  // Same-origin `/api/*` (Vercel rewrite → Worker) when no explicit URL is set.
  return API_BASE_URL || "";
}

/** Human-friendly recovery guidance per error code. */
export function describeError(error: unknown): { title: string; message: string } {
  if (error instanceof CaptionGrabError) {
    switch (error.code) {
      case "VIDEO_NOT_FOUND":
        return { title: "Video not found", message: "Check the link — the video may be deleted, private, or the URL is incomplete." };
      case "PRIVATE_VIDEO":
        return { title: "Private video", message: "This video requires sign-in, so its captions can't be reached. Try a public video." };
      case "UNPLAYABLE_VIDEO":
        return { title: "Video unavailable", message: error.message || "YouTube says this video can't be played right now." };
      case "NO_CAPTIONS":
        return { title: "No captions found", message: "This video has no caption tracks yet. Auto-captions sometimes appear hours after upload." };
      case "LANGUAGE_UNAVAILABLE":
        return { title: "That language isn't on this video", message: error.message || "Pick one of the listed tracks, or turn on smart auto-translate in Preferences." };
      case "TRANSCRIPT_UNAVAILABLE":
        return { title: "Transcript blocked", message: error.message };
      case "RATE_LIMITED":
        return { title: "Slow down a little", message: error.message || "Too many requests — please wait a moment and retry." };
      case "TIMEOUT":
        return { title: "Request timed out", message: "YouTube is responding slowly. Please try again." };
      case "NETWORK_ERROR":
        return {
          title: "Can't reach the API",
          message:
            "The CaptionGrab API isn't reachable. If you're running locally, start the Worker (`npm run worker:dev`); otherwise check your connection.",
        };
      case "UPSTREAM_ERROR":
        return { title: "YouTube hiccup", message: error.message || "YouTube didn't respond. Wait a moment and retry." };
      default:
        return { title: "Something went wrong", message: error.message || "Please try again." };
    }
  }
  if (error instanceof Error) return { title: "Something went wrong", message: error.message };
  return { title: "Something went wrong", message: "An unexpected error occurred. Please try again." };
}

async function request<T>(path: string): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), API_TIMEOUT_MS);
  let res: Response;
  try {
    res = await fetch(`${baseUrl()}${path}`, {
      signal: controller.signal,
      headers: { accept: "application/json" },
    });
  } catch (e) {
    clearTimeout(timer);
    if (e instanceof DOMException && e.name === "AbortError") {
      throw new CaptionGrabError("TIMEOUT", "The request timed out.");
    }
    throw new CaptionGrabError("NETWORK_ERROR", "Network request failed.");
  } finally {
    clearTimeout(timer);
  }

  let body: unknown = null;
  try {
    body = await res.json();
  } catch {
    // Non-JSON upstream (proxy misconfiguration, gateway HTML, ...).
  }

  if (!res.ok) {
    const err = (body as { error?: { code?: string; message?: string } } | null)?.error;
    const code = (err?.code as ApiErrorCode) || (res.status === 429 ? "RATE_LIMITED" : "UPSTREAM_ERROR");
    const retryAfter = Number(res.headers.get("retry-after") || 0) || undefined;
    throw new CaptionGrabError(code, err?.message || `Request failed (${res.status}).`, retryAfter);
  }
  return body as T;
}

export function fetchVideoInfo(videoId: string): Promise<VideoInfo> {
  return request<VideoInfo>(`/api/video?id=${encodeURIComponent(videoId)}`);
}

export interface TranscriptOptions {
  /**
   * Allow the API to fall back to another track and machine-translate when the
   * requested language is missing. `false` makes a missing language an error
   * the user can act on instead of a silent substitution.
   */
  translate?: boolean;
}

export function fetchTranscript(
  videoId: string,
  lang = "en",
  opts: TranscriptOptions = {},
): Promise<TranscriptResult> {
  const translate = opts.translate === false ? "0" : "1";
  return request<TranscriptResult>(
    `/api/transcript?id=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(lang)}&translate=${translate}`,
  );
}

export interface ApiHealth {
  reachable: boolean;
  /** True when answers are coming from the dev offline demo library. */
  demo: boolean;
}

export async function checkApiHealth(): Promise<ApiHealth> {
  try {
    const res = await request<{ ok: boolean; demo?: boolean; degraded?: boolean }>("/api/health");
    return { reachable: res?.ok === true, demo: Boolean(res?.demo || res?.degraded) };
  } catch {
    return { reachable: false, demo: false };
  }
}
