import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { LIMITS, LOCAL_STORAGE_KEYS } from "@/config/apiConfig";
import type { TranscriptResult, TranscriptSegment } from "@/lib/api";

export interface HistoryEntry {
  id: string;
  videoId: string;
  title: string;
  author: string;
  thumbnail: string;
  language: string;
  languageName: string;
  translated: boolean;
  isAutoGenerated: boolean;
  wordCount: number;
  segmentCount: number;
  createdAt: number;
  text: string;
  segments: TranscriptSegment[];
}

interface HistoryContextValue {
  entries: HistoryEntry[];
  count: number;
  add: (result: TranscriptResult, thumbnail: string) => void;
  remove: (id: string) => void;
  clear: () => void;
}

const HistoryContext = createContext<HistoryContextValue | undefined>(undefined);

function load(): HistoryEntry[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEYS.HISTORY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as HistoryEntry[];
    if (!Array.isArray(parsed)) return [];
    // Guard against entries written by an older shape.
    return parsed.filter((e) => e && typeof e.id === "string" && Array.isArray(e.segments));
  } catch {
    return [];
  }
}

function persist(entries: HistoryEntry[]): void {
  try {
    localStorage.setItem(LOCAL_STORAGE_KEYS.HISTORY, JSON.stringify(entries));
  } catch {
    // Quota exceeded — halve and retry once, then give up quietly.
    try {
      localStorage.setItem(
        LOCAL_STORAGE_KEYS.HISTORY,
        JSON.stringify(entries.slice(0, Math.floor(entries.length / 2))),
      );
    } catch {
      /* history is a convenience, never critical */
    }
  }
}

/**
 * Single source of truth for local extraction history.
 *
 * This is a context on purpose: the extractor writes to it and the history
 * panel reads from it, and they must see the same list in the same render.
 */
export const HistoryProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [entries, setEntries] = useState<HistoryEntry[]>([]);

  useEffect(() => {
    setEntries(load());
  }, []);

  const add = useCallback((result: TranscriptResult, thumbnail: string) => {
    setEntries((prev) => {
      const entry: HistoryEntry = {
        id: `${result.videoId}:${result.language}:${Date.now()}`,
        videoId: result.videoId,
        title: result.title,
        author: result.author,
        thumbnail,
        language: result.language,
        languageName: result.languageName,
        translated: result.translated,
        isAutoGenerated: result.isAutoGenerated,
        wordCount: result.text ? result.text.split(/\s+/).filter(Boolean).length : 0,
        segmentCount: result.segments.length,
        createdAt: Date.now(),
        text: result.text.slice(0, LIMITS.HISTORY_PREVIEW_CHARS * 10),
        segments: result.segments,
      };
      const next = [
        entry,
        ...prev.filter((e) => !(e.videoId === entry.videoId && e.language === entry.language)),
      ].slice(0, LIMITS.MAX_HISTORY_ENTRIES);
      persist(next);
      return next;
    });
  }, []);

  const remove = useCallback((id: string) => {
    setEntries((prev) => {
      const next = prev.filter((e) => e.id !== id);
      persist(next);
      return next;
    });
  }, []);

  const clear = useCallback(() => {
    setEntries([]);
    try {
      localStorage.removeItem(LOCAL_STORAGE_KEYS.HISTORY);
    } catch {
      /* noop */
    }
  }, []);

  const value = useMemo<HistoryContextValue>(
    () => ({ entries, count: entries.length, add, remove, clear }),
    [entries, add, remove, clear],
  );

  return <HistoryContext.Provider value={value}>{children}</HistoryContext.Provider>;
};

export function useCaptionHistory(): HistoryContextValue {
  const ctx = useContext(HistoryContext);
  if (!ctx) throw new Error("useCaptionHistory must be used within a HistoryProvider");
  return ctx;
}
