import { useCallback, useEffect, useState } from "react";
import { LIMITS, LOCAL_STORAGE_KEYS } from "@/config/apiConfig";
import type { TranscriptResult, TranscriptSegment } from "@/lib/api";

export interface HistoryEntry {
  id: string;
  videoId: string;
  title: string;
  author: string;
  thumbnail: string;
  language: string;
  languageName: string;
  translated: boolean;
  isAutoGenerated: boolean;
  wordCount: number;
  segmentCount: number;
  createdAt: number;
  text: string;
  segments: TranscriptSegment[];
}

function load(): HistoryEntry[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEYS.HISTORY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as HistoryEntry[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function persist(entries: HistoryEntry[]): void {
  try {
    localStorage.setItem(LOCAL_STORAGE_KEYS.HISTORY, JSON.stringify(entries));
  } catch {
    // Storage full or unavailable — drop oldest entries and retry once.
    try {
      localStorage.setItem(
        LOCAL_STORAGE_KEYS.HISTORY,
        JSON.stringify(entries.slice(0, Math.floor(entries.length / 2))),
      );
    } catch {
      /* give up silently; history is a convenience, not critical */
    }
  }
}

export function useCaptionHistory() {
  const [entries, setEntries] = useState<HistoryEntry[]>([]);

  useEffect(() => {
    setEntries(load());
  }, []);

  const add = useCallback((result: TranscriptResult, thumbnail: string) => {
    setEntries((prev) => {
      const entry: HistoryEntry = {
        id: `${result.videoId}:${result.language}:${Date.now()}`,
        videoId: result.videoId,
        title: result.title,
        author: result.author,
        thumbnail,
        language: result.language,
        languageName: result.languageName,
        translated: result.translated,
        isAutoGenerated: result.isAutoGenerated,
        wordCount: result.text ? result.text.split(/\s+/).filter(Boolean).length : 0,
        segmentCount: result.segments.length,
        createdAt: Date.now(),
        text: result.text.slice(0, LIMITS.HISTORY_PREVIEW_CHARS * 10),
        segments: result.segments,
      };
      // De-duplicate same video+language, newest first, capped.
      const next = [
        entry,
        ...prev.filter((e) => !(e.videoId === entry.videoId && e.language === entry.language)),
      ].slice(0, LIMITS.MAX_HISTORY_ENTRIES);
      persist(next);
      return next;
    });
  }, []);

  const remove = useCallback((id: string) => {
    setEntries((prev) => {
      const next = prev.filter((e) => e.id !== id);
      persist(next);
      return next;
    });
  }, []);

  const clear = useCallback(() => {
    setEntries([]);
    try {
      localStorage.removeItem(LOCAL_STORAGE_KEYS.HISTORY);
    } catch {
      /* noop */
    }
  }, []);

  return { entries, add, remove, clear, count: entries.length };
}
