import React from "react";
import { Clock3, FileText, History, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useCaptionHistory, type HistoryEntry } from "@/hooks/useCaptionHistory";
import type { TranscriptResult } from "@/lib/api";
import { formatCount } from "@/lib/format";

interface Props {
  onRestore: (result: TranscriptResult, thumbnail: string) => void;
}

function timeAgo(ts: number): string {
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(ts).toLocaleDateString();
}

function toResult(entry: HistoryEntry): TranscriptResult {
  return {
    videoId: entry.videoId,
    title: entry.title,
    author: entry.author,
    requestedLanguage: entry.language,
    language: entry.language,
    languageName: entry.languageName,
    isAutoGenerated: entry.isAutoGenerated,
    translated: entry.translated,
    segments: entry.segments,
    text: entry.text,
  };
}

const HistoryPanel: React.FC<Props> = ({ onRestore }) => {
  const { entries, remove, clear, count } = useCaptionHistory();

  if (entries.length === 0) return null;

  return (
    <section aria-label="Recent extractions" className="mt-10">
      <div className="flex items-center justify-between gap-3">
        <h2 className="flex items-center gap-2 font-display text-lg font-bold">
          <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <History className="h-4 w-4" />
          </span>
          Recent extractions
          <Badge variant="secondary" className="rounded-full">
            {count}
          </Badge>
        </h2>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => {
            clear();
            toast.success("History cleared");
          }}
          className="gap-1.5 rounded-xl text-xs text-muted-foreground"
        >
          <Trash2 className="h-3.5 w-3.5" /> Clear all
        </Button>
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        {entries.map((entry) => (
          <article
            key={entry.id}
            className="group flex gap-3 rounded-2xl border border-border/60 bg-card/60 p-3 transition-all hover:border-primary/40 hover:shadow-[0_12px_40px_-16px_rgba(99,91,255,0.5)]"
          >
            <button
              type="button"
              onClick={() => onRestore(toResult(entry), entry.thumbnail)}
              className="relative block w-32 shrink-0 overflow-hidden rounded-xl text-left"
              aria-label={`Reopen transcript for ${entry.title}`}
            >
              <img
                src={entry.thumbnail}
                alt=""
                loading="lazy"
                className="aspect-video w-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
            </button>
            <div className="min-w-0 flex-1">
              <button
                type="button"
                onClick={() => onRestore(toResult(entry), entry.thumbnail)}
                className="block w-full text-left"
              >
                <h3 className="line-clamp-2 text-sm font-semibold leading-snug transition-colors group-hover:text-primary">
                  {entry.title}
                </h3>
              </button>
              <p className="mt-0.5 truncate text-xs text-muted-foreground">{entry.author}</p>
              <div className="mt-1.5 flex flex-wrap items-center gap-x-2.5 gap-y-1 text-[0.7rem] text-muted-foreground">
                <span className="inline-flex items-center gap-1">
                  <FileText className="h-3 w-3" /> {formatCount(entry.wordCount)} words
                </span>
                <span>{entry.languageName}</span>
                <span className="inline-flex items-center gap-1">
                  <Clock3 className="h-3 w-3" /> {timeAgo(entry.createdAt)}
                </span>
              </div>
            </div>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => remove(entry.id)}
              aria-label={`Remove ${entry.title} from history`}
              className="h-8 w-8 shrink-0 self-start rounded-lg text-muted-foreground opacity-0 transition-opacity hover:text-destructive group-hover:opacity-100 focus:opacity-100"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </Button>
          </article>
        ))}
      </div>
      <p className="mt-3 text-xs text-muted-foreground">
        History lives only in this browser — clearing site data removes it. Nothing is uploaded.
      </p>
    </section>
  );
};

export default HistoryPanel;
