/**
 * `captiongrab:dev-api` — a dev-server middleware for `/api/*`.  DEV ONLY.
 *
 * Order of operations for every request:
 *   1. Proxy to the real Cloudflare Worker (`npm run worker:dev`, port 8787).
 *      If it answers, its response is passed straight through untouched.
 *   2. If the Worker is not reachable, answer from the offline demo library
 *      (`dev/demoLibrary.ts`) so the whole UI still works end-to-end.
 *      Those responses carry `demo: true` plus an `x-captiongrab-source`
 *      header, and the app labels them clearly as demo data.
 *
 * Step 2 reuses the production transcript code (`worker/src/transcript.ts`):
 * track selection, translation fallback and json3 parsing are the real thing,
 * not a re-implementation.
 */

import type { IncomingMessage, ServerResponse } from "node:http";
import type { Plugin } from "vite";
import {
  assembleText,
  parseJson3,
  selectTrack,
  type ResolvedTrack,
} from "../worker/src/transcript";
import { findDemoVideo, toJson3 } from "../dev/demoLibrary";

const WORKER_ORIGIN = process.env.WORKER_ORIGIN || "http://127.0.0.1:8787";
const WORKER_TIMEOUT_MS = 1200;

const VIDEO_ID_RE = /^[a-zA-Z0-9_-]{11}$/;
const LANG_RE = /^[a-zA-Z]{2,3}(?:[-_][a-zA-Z]{2,4})?$/;

function send(res: ServerResponse, status: number, body: unknown, extra: Record<string, string> = {}) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "content-length": Buffer.byteLength(payload),
    "cache-control": "no-store",
    ...extra,
  });
  res.end(payload);
}

function normalizeLang(lang: string | null): string {
  if (!lang) return "en";
  const trimmed = lang.trim().replace("_", "-");
  if (!LANG_RE.test(trimmed)) return "en";
  return trimmed.toLowerCase();
}

/** Try the real Worker first; returns null when it is not answering. */
async function proxyToWorker(fullPath: string): Promise<Response | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), WORKER_TIMEOUT_MS);
  try {
    return await fetch(`${WORKER_ORIGIN}${fullPath}`, { signal: controller.signal });
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

async function pipe(upstream: Response, res: ServerResponse): Promise<void> {
  const headers: Record<string, string> = { "x-captiongrab-source": "worker" };
  upstream.headers.forEach((value, key) => {
    // Let the dev server own framing/encoding.
    if (["content-length", "transfer-encoding", "connection"].includes(key.toLowerCase())) return;
    headers[key] = value;
  });
  const body = Buffer.from(await upstream.arrayBuffer());
  res.writeHead(upstream.status, headers);
  res.end(body);
}

/** Offline answer for `/api/video`. */
function demoVideo(videoId: string) {
  const video = findDemoVideo(videoId);
  return {
    videoId: video.videoId,
    title: video.title,
    author: video.author,
    lengthSeconds: video.lengthSeconds,
    viewCount: video.viewCount,
    thumbnail: `https://i.ytimg.com/vi/${video.videoId}/hqdefault.jpg`,
    captionsAvailable: video.tracks.length > 0,
    tracks: video.tracks.map((t) => ({
      languageCode: t.languageCode,
      languageName: t.name,
      kind: t.kind,
      translatable: t.translatable,
    })),
    demo: true,
  };
}

/** Offline answer for `/api/transcript` — runs the real parser + selector. */
function demoTranscript(videoId: string, requestedLang: string, allowTranslate: boolean) {
  const video = findDemoVideo(videoId);
  const tracks: ResolvedTrack[] = video.tracks.map((t) => ({
    baseUrl: `https://demo.invalid/timedtext?v=${videoId}&lang=${t.languageCode}`,
    languageCode: t.languageCode,
    name: t.name,
    kind: t.kind,
    translatable: t.translatable,
  }));

  const { track, servedLang, translated } = selectTrack(tracks, requestedLang, { allowTranslate });
  const wantsTranslation =
    translated && servedLang.toLowerCase().split(/[-_]/)[0] !== requestedLang.split("-")[0];

  // Parse a genuine json3 document with the production parser.
  const segments = parseJson3(toJson3(video));

  return {
    videoId,
    title: video.title,
    author: video.author,
    requestedLanguage: requestedLang,
    language: wantsTranslation ? requestedLang : servedLang,
    languageName: wantsTranslation ? languageDisplayName(requestedLang, track.name) : track.name,
    sourceLanguage: servedLang,
    sourceLanguageName: track.name,
    isAutoGenerated: track.kind === "auto",
    translated: wantsTranslation,
    segments,
    text: assembleText(segments),
    demo: true,
  };
}

/** Human name for a BCP-47 tag, with a graceful fallback. */
function languageDisplayName(tag: string, fallback: string): string {
  try {
    const name = new Intl.DisplayNames(["en"], { type: "language" }).of(tag);
    return name && name.length > 0 ? name : fallback;
  } catch {
    return fallback;
  }
}

export function devApiPlugin(): Plugin {
  return {
    name: "captiongrab:dev-api",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use("/api", (req: IncomingMessage, res: ServerResponse) => {
        void handle(req, res);
      });
    },
  };
}

async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
  // `server.middlewares.use("/api", ...)` strips the mount path, so re-add it.
  const fullPath = `/api${req.url || "/"}`;

  // 1. Real Worker wins whenever it is up.
  const upstream = await proxyToWorker(fullPath);
  if (upstream) return pipe(upstream, res);

  // 2. Offline demo fallback.
  const url = new URL(fullPath, "http://dev.invalid");
  const path = url.pathname.replace(/\/+$/, "") || "/";
  const demo = { "x-captiongrab-source": "offline-demo" };

  if (path === "/api/health") {
    return send(
      res,
      200,
      {
        ok: true,
        service: "captiongrab-api",
        degraded: true,
        demo: true,
        time: new Date().toISOString(),
      },
      demo,
    );
  }

  if (path === "/api/video") {
    const id = (url.searchParams.get("id") || "").trim();
    if (!VIDEO_ID_RE.test(id)) {
      return send(
        res,
        400,
        { error: { code: "INVALID_VIDEO_ID", message: "Provide a valid 11-character YouTube video id." } },
        demo,
      );
    }
    return send(res, 200, demoVideo(id), demo);
  }

  if (path === "/api/transcript") {
    const id = (url.searchParams.get("id") || "").trim();
    const lang = normalizeLang(url.searchParams.get("lang"));
    const allowTranslate = url.searchParams.get("translate") !== "0";
    if (!VIDEO_ID_RE.test(id)) {
      return send(
        res,
        400,
        { error: { code: "INVALID_VIDEO_ID", message: "Provide a valid 11-character YouTube video id." } },
        demo,
      );
    }
    try {
      return send(res, 200, demoTranscript(id, lang, allowTranslate), demo);
    } catch {
      return send(
        res,
        404,
        {
          error: {
            code: "LANGUAGE_UNAVAILABLE",
            message: `No ${lang} captions in the demo library, and auto-translate is turned off.`,
          },
        },
        demo,
      );
    }
  }

  return send(res, 404, { error: { code: "NOT_FOUND", message: `Unknown endpoint: ${path}` } }, demo);
}
