/**
 * Render smoke tests.
 *
 * These mount the real component tree with `react-dom/server`, which runs
 * every component's render path in Node — no browser needed. They catch the
 * class of bug that unit tests miss: a missing import, a bad hook order, an
 * undefined prop, a component that throws on first paint.
 *
 * Effects (IntersectionObserver, fetch, timers) don't run here; those paths are
 * covered by the API-level tests and the dev-server end-to-end check.
 */

import React from "react";
import { describe, expect, it } from "vitest";

/**
 * react-router and Radix call `useLayoutEffect`, which React warns about during
 * server rendering. Nothing here hydrates, so the warning is pure noise — swap
 * it for `useEffect` for the duration of this file.
 */
React.useLayoutEffect = React.useEffect;
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SettingsProvider } from "@/contexts/SettingsContext";
import { HistoryProvider } from "@/contexts/HistoryContext";
import Index from "@/pages/Index";
import About from "@/pages/About";
import Privacy from "@/pages/Privacy";
import Terms from "@/pages/Terms";
import NotFound from "@/pages/NotFound";
import CaptionDisplay from "@/components/CaptionDisplay";
import type { TranscriptResult } from "@/lib/api";

function render(node: React.ReactElement, route = "/"): string {
  return renderToStaticMarkup(
    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
      <SettingsProvider>
        <HistoryProvider>
          <TooltipProvider>
            <MemoryRouter initialEntries={[route]}>{node}</MemoryRouter>
          </TooltipProvider>
        </HistoryProvider>
      </SettingsProvider>
    </ThemeProvider>,
  );
}

describe("page renders", () => {
  it("renders the home page with its full section composition", () => {
    const html = render(<Index />);
    // Hero
    expect(html).toContain("Every word,");
    expect(html).toContain("timestamped.");
    expect(html).toContain("Grab a transcript");
    // Extractor
    expect(html).toContain("Paste a YouTube link");
    expect(html).toContain("No link handy? Try a sample");
    // Feature bento
    expect(html).toContain("One link, any shape");
    expect(html).toContain("Private local history");
    // How it works
    expect(html).toContain("Link to transcript in");
    expect(html).toContain("Paste the link");
    // Stats, languages, FAQ, CTA
    expect(html).toContain("Caption languages");
    expect(html).toContain("Español");
    expect(html).toContain("Is CaptionGrab really free?");
    expect(html).toContain("Start reading video.");
    // Anchors the nav depends on
    expect(html).toContain('id="extractor"');
    expect(html).toContain('id="features"');
    expect(html).toContain('id="how-it-works"');
    expect(html).toContain('id="faq"');
  });

  it("renders the transcript ticker demo", () => {
    const html = render(<Index />);
    expect(html).toContain("transcript · live");
    expect(html).toContain("streaming");
  });

  it.each([
    ["About", <About key="a" />, "We fix that."],
    ["Privacy", <Privacy key="p" />, "Privacy Policy"],
    ["Terms", <Terms key="t" />, "Terms of Service"],
    ["NotFound", <NotFound key="n" />, "off-script."],
  ])("renders %s without throwing", (_name, page, marker) => {
    const html = render(page);
    expect(html).toContain(marker);
    expect(html).toContain("CaptionGrab");
  });
});

describe("CaptionDisplay", () => {
  const result: TranscriptResult = {
    videoId: "8jPQjjsBbIc",
    title: "Demo reel — The quiet power of subtitles",
    author: "CaptionGrab Demo Library",
    requestedLanguage: "en",
    language: "en",
    languageName: "English",
    sourceLanguage: "en",
    sourceLanguageName: "English",
    isAutoGenerated: false,
    translated: false,
    segments: [
      { start: 0.4, dur: 3.8, text: "For most of the twentieth century, captions were an afterthought." },
      { start: 4.6, dur: 4.1, text: "They were designed for people who could not hear at all." },
      { start: 9.1, dur: 3.4, text: "And then something strange happened online." },
    ],
    text:
      "For most of the twentieth century, captions were an afterthought. They were designed for people who could not hear at all. And then something strange happened online.",
  };

  it("renders stats, toolbar and every segment", () => {
    const html = render(<CaptionDisplay result={result} thumbnail="/poster-fallback.svg" />);
    expect(html).toContain("Your transcript is ready");
    expect(html).toContain("Demo reel");
    expect(html).toContain("English");
    expect(html).toContain("Creator captions");
    // All three segments rendered with their timecodes
    expect(html).toContain("00:00");
    expect(html).toContain("00:04");
    expect(html).toContain("00:09");
    expect(html).toContain("afterthought");
    // Toolbar
    expect(html).toContain("Copy text");
    expect(html).toContain("Search within the transcript…");
    expect(html).toContain("Export");
  });

  it("labels machine-translated transcripts and names the source language", () => {
    const html = render(
      <CaptionDisplay
        result={{
          ...result,
          language: "ja",
          languageName: "Japanese",
          requestedLanguage: "ja",
          translated: true,
          sourceLanguage: "en",
          sourceLanguageName: "English",
        }}
        thumbnail="/poster-fallback.svg"
      />,
    );
    expect(html).toContain("Japanese");
    expect(html).toContain("Translated from English");
  });
});
