/**
 * Regression test for the history round-trip.
 *
 * The stored `text` field is length-capped to stay inside the localStorage
 * quota, while `segments` is always complete. Restoring an entry must
 * therefore rebuild the transcript text from the segments — otherwise any
 * video over ~40k characters came back truncated and "Copy text" / .txt
 * export silently lost the tail of the transcript.
 */

import { describe, expect, it } from "vitest";
import { buildEntry, entryToResult } from "@/contexts/HistoryContext";
import type { TranscriptResult } from "@/lib/api";
import { LIMITS } from "@/config/apiConfig";

/** A realistic 60-minute talk: 9,000 words of ~6 characters each. */
function makeLongTranscript(minutes = 60): TranscriptResult {
  const segments = [];
  const totalWords = minutes * 150;
  let t = 0;
  while (segments.flat().length < totalWords) {
    const words = ["the", "caption", "pipeline", "streams", "every", "word", "with", "a", "real", "timecode"];
    const text = words.join(" ");
    segments.push({ start: t, dur: 4, text });
    t += 4.2;
    if (segments.length * words.length >= totalWords) break;
  }
  const text = segments.map((s) => s.text).join(" ");
  return {
    videoId: "aaaaaaaaaaa",
    title: "A very long lecture",
    author: "Someone",
    requestedLanguage: "en",
    language: "en",
    languageName: "English",
    isAutoGenerated: false,
    translated: false,
    segments,
    text,
  };
}

describe("history storage round-trip", () => {
  const original = makeLongTranscript(60);
  const cap = LIMITS.HISTORY_PREVIEW_CHARS * 10;

  it("builds a fixture that is genuinely longer than the storage cap", () => {
    // Guards the test itself: if the fixture shrank, the assertion below is vacuous.
    expect(original.text.length).toBeGreaterThan(cap);
    // 900 segments at ~4.2s each is a ~63 minute talk.
    expect(original.segments.length).toBe(900);
  });

  it("caps the stored preview text", () => {
    const entry = buildEntry(original, "/poster-fallback.svg");
    expect(entry.text.length).toBe(cap);
    expect(entry.text.length).toBeLessThan(original.text.length);
  });

  it("keeps every segment in storage", () => {
    const entry = buildEntry(original, "/poster-fallback.svg");
    expect(entry.segments).toHaveLength(original.segments.length);
    expect(entry.wordCount).toBe(original.text.split(/\s+/).filter(Boolean).length);
  });

  it("restores the FULL transcript text, not the truncated preview", () => {
    const restored = entryToResult(buildEntry(original, "/poster-fallback.svg"));
    expect(restored.text).toBe(original.text);
    expect(restored.text.length).toBeGreaterThan(cap);
  });

  it("restores the same word count the live extraction reported", () => {
    const restored = entryToResult(buildEntry(original, "/poster-fallback.svg"));
    const count = (s: string) => s.trim().split(/\s+/).filter(Boolean).length;
    expect(count(restored.text)).toBe(count(original.text));
  });

  it("falls back to the stored preview when an entry has no segments", () => {
    const entry = { ...buildEntry(original, "/x.svg"), segments: [], text: "legacy preview" };
    expect(entryToResult(entry).text).toBe("legacy preview");
  });
});
